Update @context URLs, add response contentType workaround
vaimee/zion pull request #52
Opened 2023-04-23 08:06 UTC by JKRhb

This PR updates the @context URLs included in the directory's TM/TD in anticipation of https://github.com/w3c/wot-discovery/pull/471 and applies the workaround added in https://github.com/w3c/wot-discovery/pull/469 to the `ThingDescriptionBuilderService`.

Combined, these changes result in a TD for the Directory that [passes validation](https://www.jsonschemavalidator.net/s/0hdr6hBo) against the latest [JSON Schema document](https://github.com/w3c/wot-thing-description/blob/main/validation/td-json-schema-validation.json) provided in the TD repository :)

2023-04-23 10:14 UTC, JKRhb commented
Needed to update two dependencies and create another workaround in 8f0b128 to get the TD instantiation to actually work again. Seems to me like a bug has appeared in the `td-tools` package that modifies the input TM, which apparently has not happened before 🤔

2023-04-28 08:38 UTC, relu91 requested changes
Hi Jan! As always thank you really much for contributing to Zion. The changes look good, but I checked the difference in package-lock and saw changes in unrelated packages like Fastify. Do you have an idea why this is happening? Can you try to narrow down the changes to only node-wot and wot-thing-description-types packages?

2023-04-28 08:41 UTC, JKRhb commented
Hi Cristiano, thank you for the feedback! Sure, I will check again and try to narrow down the changes :)

2023-04-28 14:35 UTC, JKRhb commented
With the latest push, I managed to trim down the changes in the `package-lock.json` a lot. However, for some reason, the tests are now failing since the `td-tools` apparently does not include the latest fixes for the TM JSON schema 🤔 We may need to put this PR on hold then until version 0.8.6 of the `td-tools` package with the updated schema has been released.

2023-05-03 15:26 UTC, relu91 commented
> 

Ok, in my understanding we are going to release 0.8.6 very soon. I'll check if we get the green light once it will be published!

2023-05-05 10:28 UTC, JKRhb commented
The new `td-tools` release actually solved the problem 🎉

2023-05-05 10:29 UTC, JKRhb commented
I am now wondering: Should we wait for https://github.com/w3c/wot-discovery/pull/471? Or would it be fine to already merge this PR?

2023-05-23 17:34 UTC, relu91 commented
Talked offline with @hyperloris, he was a little bit uncomfortable with merging a PR with TODOs in it. I agree but those TODOs are reasonable and they can be tracked in issues (as suggested by @hyperloris  himself). Therefore, I'm forcing the merging of the PR without waiting for his formal approval. Later on, I'll open the tracking issues.

2023-05-23 17:34 UTC, merged